version: 2
jobs:
  test_node_8:
    docker:
      - image: circleci/node:8
        environment:
          ENV: CI
          TERM: dumb # See: https://github.com/facebook/flow/pull/3305
          JEST_JUNIT_OUTPUT: ./artifacts/junit.xml
    steps:
      - checkout
      - run:
          name: Pre-Dependencies
          command: mkdir -p /tmp/allocloud-sdk-js/artifacts
      - restore_cache:
          keys:
            - v1-dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-dependency-cache-{{ .Branch }}
            - v1-dependency-cache-master-{{ checksum "yarn.lock" }}
            - v1-dependency-cache-master
      - run:
          name: Install Node Modules
          command: yarn install
      - save_cache:
          key: v1-dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - /tmp/allocloud-sdk-js/node_modules
      - run:
          name: Run unit tests
          command: yarn run ci
      - store_test_results:
          path: /tmp/allocloud-sdk-js/artifacts
  release:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npx semantic-release

workflows:
  version: 2
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - test_node_8
      - release:
          requires:
            - test_node_8
